Rename to SSO Kit
vaadin/sso-kit pull request #35
Opened 2022-09-14 08:38 UTC by heruan

This performs the following renaming:

- `auth` -> `sso-kit`
- `auth-start` -> `sso-kit-starter`
- `auth-demo` -> `sso-kit-demo`
- `com.vaadin.auth.*` -> `com.vaadin.sso.*`
- `VaadinAuthSecurityConfiguration` -> `SingleSignOnConfiguration`
- Spring properties `vaadin.auth.*` -> `vaadin.sso.*`

and other minor classes accordingly.

2022-09-14 11:55 UTC, DiegoCardoso requested changes
Apart from the minor changes that I pointed out, another "nit" is that the theme on the demo project still references to `auth-demo`.

2022-09-14 11:55 UTC, DiegoCardoso commented on pom.xml
> +</project>
nit: restore newline

2022-09-14 11:55 UTC, DiegoCardoso commented on sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java
> +    static class DefaultVaadinAuthContext implements AuthenticationContext {
Shouldn't the class be also renamed to something like `DefaultAuthenticationContext`?
Same thing would apply to the property name defined on line `61`.

2022-09-14 11:55 UTC, DiegoCardoso commented on sso-kit-starter/src/main/resources/META-INF/spring.factories
> +com.vaadin.sso.starter.SsoKitConfiguration
nit: add newline at the end of the file

2022-09-14 12:04 UTC, heruan commented
> Apart from the minor changes that I pointed out, another "nit" is that the theme on the demo project still references to `auth-demo`.

Right! I've renamed also the theme now.

2022-09-14 12:11 UTC, DiegoCardoso approved these changes

2022-09-14 12:16 UTC, merged

2022-09-15 12:42 UTC, jouni commented
Rename the repo to sso-kit as well?

2022-09-15 12:57 UTC, heruan commented
> Rename this repo to sso-kit as well?

Yes, it's planned! It requires some changes to CI/CD so we'll do presumably next week.