Use UIDL aware logout redirect strategy
vaadin/sso-kit pull request #43
Opened 2022-09-27 21:34 UTC by heruan

Adds a custom UIDL aware logout redirect strategy and calls the logout success-handler inside `UI::accessSynchronously`.

Closes #42

2022-09-30 12:32 UTC, tamasmak commented on sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java
> +                            + "provide of the user logout", e);
Should be provider instead of provide.

2022-09-30 12:33 UTC, tamasmak requested changes

2022-09-30 12:33 UTC, tamasmak commented on sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java
> +                            + "provide of the user logout", e);
Should be provider instead of provide.

2022-10-03 10:00 UTC, heruan commented on sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java
> +                            + "provide of the user logout", e);
Fixed, thanks!

2022-10-03 11:11 UTC, tamasmak approved these changes

2022-10-03 12:04 UTC, merged